---
title: Highlights
url: http://highlights.sawyerhollenshead.com
timezone: UTC
collections:
  books:
    title: Books
    output: true
  highlights:
    title: Highlights
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
- scope:
    path: "highlights"
  values:
    layout: "highlight"
permalinks: pretty
exclude: ['node_modules', 'bower_components', 'siteleaf-gem']