---
title: Highlights
url: http://highlights.sawyerhollenshead.com
timezone: America/New_York
collections:
  books:
    title: Books
    output: true
  highlights:
    title: Highlights
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
- scope:
    path: highlights
  values:
    layout: highlight
- scope:
    path: books
  values:
    layout: book
permalinks: pretty
exclude:
- node_modules
- bower_components
- siteleaf-gem